name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [main] # Cambia si tu rama principal no es main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - uses: actions/checkout@v4

      # 2️⃣ Configurar Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Instalar dependencias y build del frontend
      - name: Install dependencies
        run: npm ci
        working-directory: FrontEnd

      - name: Build Frontend
        run: npm run build
        working-directory: Frontend

      # 4️⃣ Deploy a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: FrontEnd/dist